### ISSUE TITLE
Unable to run frontend with version 1.01 under folder that is not "free5gc"

### ISSUE THREAD

**Issue by mmadnac1313** [free5gc/webconsole#10]
yy-VirtualBox:~/free5gc305/webconsole$ go run server.go 
2021-06-26T22:52:57+08:00 [INFO][WebUI][App] webui
2021-06-26T22:52:57+08:00 [INFO][WebUI][App] webconsole version:  
	Not specify ldflags (which link version) during go build
	go version: go1.14.4 linux/amd64
panic: [Configuration] open ../../../../tmp/go-build484513399/b001/config/webuicfg.yaml: no such file or directory

goroutine 1 [running]:
github.com/free5gc/webconsole/backend/webui_service.(*WEBUI).Initialize(0x180e2e0, 0xc0003a4160)
	/home/yy/free5gc305/webconsole/backend/webui_service/webui_init.go:68 +0x122
main.action(0xc0003a4160)
	/home/yy/free5gc305/webconsole/server.go:36 +0x37
github.com/urfave/cli.HandleAction(0xd427c0, 0xec57c8, 0xc0003a4160, 0xc0003a4160, 0x0)
	/home/yy/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:526 +0x7c
github.com/urfave/cli.(*App).Run(0xc000354000, 0xc0000201b0, 0x1, 0x1, 0x0, 0x0)
	/home/yy/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:286 +0x649
main.main()
	/home/yy/free5gc305/webconsole/server.go:30 +0x201
exit status 2

Although there is no such problem as running it under folder name "free5gc", it's still a little problem.

**Comment by noormohammedli** [comment]
Hello, 

I have the same problem. 

Did you solve it ?? 

thanks

**Comment by free5gc-org** [comment]
Please refer to:
https://github.com/free5gc/free5gc/wiki/Installation#d-install-webconsole

**Comment by noormohammedli** [comment]
> Please refer to:
> https://github.com/free5gc/free5gc/wiki/Installation#d-install-webconsole

Thanks for your reply, 
I am trying to deal with slice management, I have the S-NSSAI list in AMF, SMF, NSSF but I am still confused about how can I manage the slice for the UE.. for example sending traffic for slice 1, slice 2.. 
OR make the UE connect to a different slice after adding the slice details to the UE info in a registration stage or after adding them to the MongoDB.  
Thanks.

**Comment by free5gc-org** [comment]
@noormohammedli 

You can manage the slice for the UE via webconsole.
For more information, you can go to [free5gc forum](https://forum.free5gc.org/) to find related discussion or raise a new one.
