### ISSUE TITLE
Adding Subscribers with Test PLMN 001 01

### ISSUE THREAD

**Issue by mrlnc** [free5gc/webconsole#22]
Hi all,

it seems like adding subscribers does not work properly when the PLMN has leading zeroes, like Test PLMN 001 01.

Adding a subscriber:
<img width="526" alt="Screenshot 2022-03-03 at 23 10 01" src="https://user-images.githubusercontent.com/1729953/156664411-19da3edb-82f8-4a20-88d0-5ad64fb71b1d.png">

In the overview, the leading zeroes are gone:
<img width="465" alt="Screenshot 2022-03-03 at 23 10 20" src="https://user-images.githubusercontent.com/1729953/156664418-629f3612-4150-4ebd-afd3-e38ddf41d66c.png">

Same when modifying the user:
<img width="546" alt="Screenshot 2022-03-03 at 23 10 30" src="https://user-images.githubusercontent.com/1729953/156664421-fdf9f864-ca48-415a-9cd0-a9456b4179fa.png">

```
2022-03-03T23:15:15+01:00 [INFO][WebUI][App] webconsole version:  


        free5GC version: v3.0.6-7-gd8267b4
        build time:      2022-03-03T22:13:38Z
        commit hash:     +c26286b
        commit time:     2022-02-09T17:45:03Z
        go version:      go1.14.4 linux/amd64
```

**Comment by s5uishida** [comment]
Hi @mrlnc 

If this issue hasn't been resolved yet, would the following URL be helpful to you? 

https://github.com/free5gc/free5gc/issues/330

**Comment by free5gc-org** [comment]
Fix in https://github.com/free5gc/webconsole/pull/24
