### ISSUE TITLE
Failure when trying to build the WebConsole

### ISSUE THREAD

**Issue by gpbcom** [free5gc/webconsole#25]
When I want to build the Web console the following error occured : 
`Start building webconsole....
cd webconsole/frontend && \
yarn install && \
yarn build && \
rm -rf ../public && \
cp -R build ../public
yarn install v1.22.18
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
[2/4] Fetching packages...
error sass@1.50.1: The engine "node" is incompatible with this module. Expected version ">=12.0.0". Got "10.19.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
make: *** [Makefile:65: webconsole/bin/webconsole] Error 1`

I'am not familliar with web development and I don't really know how to handle it,

Could you please give me some support,

Regards

**Comment by ianchen0119** [comment]
Hi @gpbcom 

I think this problem has been solved,
You can try to build webconsole again.

Thanks.

**Comment by PrinceKotoko** [comment]
How was it resolved? I am still experiencing the problem. I am new to it and do not know how to go about it. Thank you.

**Comment by PrinceKotoko** [comment]
> When I want to build the Web console the following error occured : `Start building webconsole.... cd webconsole/frontend && \ yarn install && \ yarn build && \ rm -rf ../public && \ cp -R build ../public yarn install v1.22.18 warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json. [1/4] Resolving packages... [2/4] Fetching packages... error sass@1.50.1: The engine "node" is incompatible with this module. Expected version ">=12.0.0". Got "10.19.0" error Found incompatible module. info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command. make: *** [Makefile:65: webconsole/bin/webconsole] Error 1`
> 
> I'am not familliar with web development and I don't really know how to handle it,
> 
> Could you please give me some support,
> 
> Regards

Have you please found a solution to the challenge? If yes, please share with us. Thank you.

**Comment by ianchen0119** [comment]
@PrinceKotoko 
Please try to update your node.js.
Thanks.

**Comment by andy89923** [comment]
We have updated the instructions for building the webconsole. If you still have a problem building it, feel free to ask in a new issue. 
Also, we recommend creating a new issue at https://github.com/free5gc/free5gc.
