### ISSUE TITLE
Update/ rewrite webconsole to recent dependency versions

### ISSUE THREAD

**Issue by LaumiH** [free5gc/webconsole#35]
Hi,

I am currently trying to add some features to the webconsole that we find interesting.

While I am just starting to learn React JS development, I noticed that almost all used dependencies are outdated, which does not allow me to integrate new features easily.

I was wondering if it would be helpful to re-write the webconsole frontend, using a better integration of the used tools (babel, webpack, eslint and so on), and also make the used configuration files easier to understand. I am working on this currently because it helps me understand the code better, and I can open a PR to share my changes later.

Please contact me if you consider this a helpful contribution!

Best,
Laura

**Comment by ianchen0119** [comment]
Hi @LaumiH 

Thanks for your message.

I think your contribution is helpful to the free5GC project.
You can create the pull request directly and we will arrange the developer, who has responsible for   frontend development, to review these changes.

Thanks again.

**Comment by LaumiH** [comment]
Hi @ianchen0119,

thank you for your reply!

I have almost completed my work on this issue.

There are also a few new features I would like to share with you (in a separate PR).

As the original webconsole code is basically not existing any more (I updated almost everything), I have written a concise summary on all the changes I have made, and the decisions behind them. This will hopefully help merging the PR.

I will prepare a PR as soon as I have a mergeable version.

Cheers,
Laura

**Comment by kishiguro** [comment]
@LaumiH @ianchen0119 we have another implementation of the webconsole.  let us share it as well.

**Comment by ianchen0119** [comment]
@kishiguro 

Thanks for you contribution!

**Comment by kishiguro** [comment]
@LaumiH @ianchen0119 Just made PR https://github.com/free5gc/webconsole/pull/47
Major difference is it uses typescript and material UI for the implementation.
typescript's API type definition is generated from openapi YAML.

**Comment by LaumiH** [comment]
As PR #43 was rejected, I close this issue, because #47 is no refactoring with newer dependency versions. Please open a new issue for the different goal of using TypeScript and Material UI.
