### ISSUE TITLE
Cannot stop webconsole when core is not running

### ISSUE THREAD

**Issue by LaumiH** [free5gc/webconsole#92]
webconsole version: 1.3.1 and main branch (last checked 30-04-2024)
go version: go1.18.10 linux/amd64
default webconsole config

I cannot stop the webconsole (aka `go run server.go`) when no core is running.
After pressing Ctrl+C, it freezes and the last log output is "[INFO][WEBUI][Consumer] Send Deregister NFInstance".

Without debugging it, I suppose there either is a loop or race condition in the code, or a timeout is missing for the HTTP call to the NRF.

The expected behavior is that the webconsole process can be stopped with Ctrl+C even when no core is running.

**Comment by andy89923** [comment]
Thanks for the information. This would be fixed in #96.
