### ISSUE TITLE
Webconsole is always in debug state.

### ISSUE THREAD

**Issue by juanjuan2** [free5gc/webconsole#99]
I use free5gc v3.3.0. When I run server.go affer I run ./run.sh , webconsole log shows that webconsole is in debug state and it can not add new UE in localhost:5000.

**Comment by andy89923** [comment]
Could you provide more details about "can not add new UE in localhost:5000"?
Also, what is your config file, which is located at https://github.com/free5gc/webconsole/blob/main/config/webuicfg.yaml?

**Comment by juanjuan2** [comment]
I did not modify the configuration file webuicfg.yaml.
This is my webuicfg.yaml.
<img width="371" alt="a87689a654597a476bdf40ad297a417" src="https://github.com/free5gc/webconsole/assets/45665083/6c404fcd-b291-460d-807b-9258e65a9a00">
When I run free5gc with "./run.sh" and run webconsole with "go run server.go"，the web page will show a null page. Like this:
<img width="476" alt="fb342af1ad383dd16f0e1c6d6215153" src="https://github.com/free5gc/webconsole/assets/45665083/913431bb-709c-49d2-b6df-459e5d0d4f3e">
And webconsole in terminal will show:
<img width="365" alt="bef5b179c608e725aca0697d59c27ef" src="https://github.com/free5gc/webconsole/assets/45665083/be1ce616-44ac-4545-ab2b-3f560e06b660">
How can I deal with it? Thanks.

**Comment by juanjuan2** [comment]
I find that free5gc is no problem. It is caused by the page display ratio. Sorry.

**Comment by andy89923** [comment]
The gin release setting could refer to [this](https://stackoverflow.com/questions/46411173/how-to-set-gin-mode-to-release-mode). 

Happy to hear that you solved the problem. 
If you encounter any problems or have any questions, feel free to ask.
